# -*- coding: utf-8 -*-
"""datamakerr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nuL1lkB7ykkeCBodJv14X3cVEHLGp9ZQ
"""

import numpy as np
import pandas as pd

"""I will be using multiple datasets which i got from kaggle.
I will be doing some preprocessing on it and since it has too many categories, I'm going to club a lot of them for the sake of simpilicity.
"""

from google.colab import files
uploaded = files.upload()

pdts=pd.read_csv('BigBasket Products.csv')
food=pd.read_csv('indian_food.csv')
luxury=pd.read_csv('Luxury_Products_Apparel_Data.csv')

pdts.head()

#making a dataset where just product name and it's category is present
pp=pdts[['product','category']]
pp.head()

pp['category'].value_counts()

def categorymakerfor_pp(t):
  if t=='Beauty & Hygiene':
    return t
  if t=='Cleaning & Household' or 'Kitchen,Garden & Pets' or t=='Baby Care':
    return 'Essentials'
  if t=='Gourmet & World Food': or t=='Snacks & Branded Foods' or t=='Foodgrains, Oil & Masala':#or t=='Beverages' or t=='Bakery, Cakes & Dairy' or t=='Fruits & Vegetables' or t=='Eggs, Meat & Fish':
    return 'Food And Beverages'

for ind in pp.index:
  gg=categorymakerfor_pp(pp['category'][ind])
  pp['Categories'][ind]=gg

Categories={'Beauty & Hygiene':'Beauty & Hygiene',
            'Cleaning & Household':'Essentials',
            'Kitchen, Garden & Pets':'Essentials',
            'Baby Care':'Essentials',
            'Gourmet & World Food':'Food And Beverages',
            'Snacks & Branded Foods':'Food And Beverages',
            'Foodgrains, Oil & Masala':'Food And Beverages',
            'Beverages':'Food And Beverages',
            'Bakery, Cakes & Dairy':'Food And Beverages',
            'Fruits & Vegetables':'Food And Beverages',
            'Eggs, Meat & Fish':'Food And Beverages'
            }

pp['Categories']=pp['category'].map(Categories)

pp['Categories'].value_counts()

pp.drop(['category'],inplace=True,axis=1)

"""We start working with other datasets"""

pp.head()

food.head()

foodnew=food[['name']]

foodnew.rename(columns={'name':'product'},inplace=True)
foodnew['Categories']='Food And Beverages'

foodnew.head()

"""foodnew is ready to be added to the final dataframe as it has been categorized correclty."""

luxury.head()

lux=luxury[['ProductName']]
lux['Categories']='Luxury'
lux.rename(columns={'ProductName':'product'},inplace=True)

lux.head()

"""Now, lets see all the datasets which have been preprocessed"""

pp.head()

lux.head()

foodnew.head()

finaldata=pd.concat([pp,foodnew,lux],axis=0)

finaldata['Categories'].value_counts()

from google.colab import files
uploaded = files.upload()

offi=pd.read_csv('OfficeSupplies.csv')

offi.head()

office=offi[['Item']]
office['Categories']='Stationary'
office.rename(columns={'Item':'product'},inplace=True)

office.head()

office['Categories'].value_counts()

finalfinaldata=pd.concat([finaldata,office],axis=0)

finalfinaldata['Categories'].value_counts()

finalfinaldata.to_csv('finaldataset.csv')
files.download('finaldataset.csv')

